### ISSUE TITLE
[Configuration] [Low] Missing sllep shutdown win feature

### ISSUE THREAD

**Issue by spedruzzo** [NilsFC/Model-X#3]
Use case: I want to put in sleep my win computer with a key
Expected : when I press key the pc goes in sleep
Issue : I configured a key as sleep function (theres also power to shutdown win and wakeup only for cable not BT) but doesn't work
![image](https://github.com/user-attachments/assets/0a355158-03ac-49dd-a3b3-ded547361170)

I suspect that is not possible and those command refer to power state of chip nrf ...

**Comment by NilsFC** [comment]
I red that also other people have this type of issue with ZMK. Sounds it's related to Desktop Generic Usage Page secrtion of the HID standard.
There's already a PR waiting https://github.com/zmkfirmware/zmk/pull/2473 
It's worth a try.

**Comment by NilsFC** [comment]
Tested now a local merge of PR2473 on my PC and Sleep function works. Sadly ZMK-Studio still miss keypress behaviour tags for 'SYSTEM', so I had to hard-code the &kp in the keymap file.
However I prefer to stick to main branch of ZMK, so I'll not include some temporary merge compiled .uf2 here.
We have to wait for official merge and support. But you can compile it by your own, my config source are available here: https://github.com/NilsFC/Model-X/tree/main/Software
